<?php

namespace App\Console\Commands\Routes;

use Illuminate\Console\Command;

class RebuildStructure extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'route:restructure';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Restructring the route structure.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $dirs = scandir(base_path("routes" . DIRECTORY_SEPARATOR  . "partials"));
        unset($dirs[0]);
        unset($dirs[1]);

        $text = "<?php" . PHP_EOL;
        $text .= "// DO NOT EDIT THIS FILE. IT WILL BE AUTO-GENERATE ITSELF FROM TIME TO TIME." . PHP_EOL;
        foreach($dirs as $dir) {
            $text .= "require 'partials/{$dir}';". PHP_EOL;
        }
        file_put_contents(base_path("routes" . DIRECTORY_SEPARATOR  . "web.php"), $text);

        $this->info("WEB ROUTE RESTRUCTURED.");
    }
}
