<?php
// DO NOT EDIT THIS FILE. IT WILL BE AUTO-GENERATE ITSELF FROM TIME TO TIME.
require 'partials/auth_route.php';
require 'partials/cron_route.php';
require 'partials/domain_route.php';
require 'partials/home_route.php';
